networks:
  reddit-scraper-network:
    external: true
    name: "reddit-scraper-network"

services:

  psql-reddit-scraper:
    command:
      - "postgres"
    container_name: "psql-reddit-scraper"
    entrypoint:
      - "docker-entrypoint.sh"
    environment:
      - "POSTGRES_PASSWORD=pass123"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/15/bin"
      - "GOSU_VERSION=1.16"
      - "LANG=en_US.utf8"
      - "PG_MAJOR=15"
      - "PG_VERSION=15.4-1.pgdg120+1"
      - "PGDATA=/var/lib/postgresql/data"
    hostname: "7412173bea5c"
    image: "postgres"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:02"
    networks:
      - "reddit-scraper-network"
    ports:
      - "5433:5433/tcp"
    volumes:
      - "1465b70462aafc707ab290535c56816ddcd5c920d2c79db2c261b07ec9a534c1:/var/lib/postgresql/data"

  upbeat_kowalevski:
    command:
      - "python"
      - "main.py"
    container_name: "reddit-scraper-node"
    environment:
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
      - "PYTHON_VERSION=3.9.18"
      - "PYTHON_PIP_VERSION=23.0.1"
      - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/9af82b715db434abb94a0a6f3569f43e72157346/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=45a2bb8bf2bb5eff16fdd00faef6f29731831c7c59bd9fc2bf1f3bed511ff1fe"
    hostname: "8ad11b5b02bf"
    image: "reddit-scraper-node"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:03"
    networks:
      - "reddit-scraper-network"
    tty: true
    working_dir: "/reddit-web-scraper"

version: "3.6"

volumes:
  1465b70462aafc707ab290535c56816ddcd5c920d2c79db2c261b07ec9a534c1:
    external: true
